version: "3.9"

services:
  app:
    build: .
    container_name: posts-comments-app
    ports:
      - "8080:8080"
    environment:
      STORAGE_TYPE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: posts_comments
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: posts-comments-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: posts_comments
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
